apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: kuadrant
  namespace: {{ .Values.kuadrant.namespace }}
spec:
  limitador:
    storage:
      redis-cached:
        configSecretRef:
          name: redis-config 
