apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  creationTimestamp: null
  name: job-role-binding
  namespace: {{ .Values.kuadrant.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.kuadrant.namespace }}
